### ISSUE TITLE
Nothing Seeing

### ISSUE THREAD

**Issue by Tobias3107** [ConsoleTVs/Rankify#1]
Hello Guys,
I have a problem to use this in my Stream. I have Copy this in a File from my Desktop. And i have do what there is. I have Acktivate this chop "Local File" and choose the File. and Change the Width and the Height. But it doesnt work. also when i open this in Firefox.

**Comment by ConsoleTVs** [comment]
Hey! I'm sorry to tell you this, but due browsers disabling cross site origins, this method is no longer valid. I will need to add a simple http server in order to make it work.

Sorry for this problem!

**Comment by Tobias3107** [comment]
You are fixing this Problem?

**Comment by ConsoleTVs** [comment]
Are you in a hurry? If so, try to create a simple http server (xampp on windows) and place the folder in the htdocs. After so, add the url in obs (localhost url)

**Comment by Tobias3107** [comment]
Ah okey i can do this. I thing you have a idea to do this without that

**Comment by ConsoleTVs** [comment]
Well. I will probably setup something on my site to emulate all this soon. Perhaps it will be easier to everyone :)

**Comment by Tobias3107** [comment]
That is Nice .you should write this in the ReadME File
